target: [TUOI_THO_6THANG]
id: [NGAY_BAN_GOI, TINH_USER_DANG_KY, HUYEN_USER_DANG_KY, USER_DANG_KY,
     USER_CUM_TRUONG, STAFF_CODE_DN, HOME_TRAM, TINH_USER_DANG_KY_CU]
feature: [HOME_TINH, HOME_HUYEN, GOI_DATA, KENH_DANG_KY, GIA_GOI,
     IS_TB_4G_THUC_THANG_N, GOI_CUOC_CU, DOANH_THU_GOI_CU,
     TONG_TIEU_DUNG_N_3, TONG_TIEU_DUNG_N_2, TONG_TIEU_DUNG_N_1,
     TIEU_DUNG_TB_3_THANG_TRUOC, IS_PREPAID_PACKET, DT_GOI_FULL,
     IS_28DAYS_PERIOD, SYSTEM_CLIENT, CHUKY_GOI_N,
     IS_3K3D]
leakage: [NUM_TT_BAT_MAY,GROUP_CHANNEL_TYPE_ID,  NGAY_KICH_HOAT, GHI_NHAN_TB_DATA, GHI_NHAN_TB_15K, TONG_DOANH_THU, PS_LL_DATA_THANG_N,
     PS_LL_DATA_THANG_N1, MUAGOI_N1N2, CHENH_LECH_DOANH_THU, TONG_TIEU_DUNG_N,
     GOI_N1N2, GOI_DK_GIAHAN_PHANBO_TN1N2, CHUKY_GOI_N1N2, TB_MUAGOI_DACHUKY,
     MUAGOI_50K, TT_KHM60D_MUAGOI_50K, THU_TU_GHI_NHAN_GOI_DACHUKY,
     THU_TU_GHI_NHAN_GOI_50K60D, TONG_CUOC_GOC_THUC, SL_CHUKY_GHINHAN]
drop: [TOTAL_TV360_MB, IS_TV360_THUC, TV360_WATCH_DURATION]